

export const GET_ONLINE_USERS = "GET_ONLINE_USERS"
export const FOLLOW_REQUEST="FOLLOW_REQUEST"
export const ACCEPT_REQUEST = "ACCEPT_REQUEST"
export const REJECT_REQUEST = "REJECT_REQUEST"
export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST"
export const POST_LIKED_STATUS = "POST_LIKED_STATUS"
export const POST_COMMENT = "POST_COMMENT"
export const POST_CREATED = "POST_CREATED"
