

export const GET_ONLINE_USERS = "GET_ONLINE_USERS"
export const FOLLOW_REQUEST="FOLLOW_REQUEST"
export const ACCEPT_REQUEST = "ACCEPT_REQUEST"
export const REJECT_REQUEST = "REJECT_REQUEST"
export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST"


