

const GET_ONLINE_USERS = "GET_ONLINE_USERS"
const FOLLOW_REQUEST = "FOLLOW_REQUEST"
const ACCEPT_REQUEST = "ACCEPT_REQUEST"
const REJECT_REQUEST = "REJECT_REQUEST"
const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST"
const POST_LIKED_STATUS = "POST_LIKED_STATUS"
const POST_COMMENT = "POST_COMMENT"
const POST_CREATED = "POST_CREATED"

module.exports = {
        GET_ONLINE_USERS,
        FOLLOW_REQUEST,
        ACCEPT_REQUEST,
        REJECT_REQUEST,
        UNFOLLOW_REQUEST,
        POST_LIKED_STATUS,
        POST_COMMENT,
        POST_CREATED
}